baseURL = 'https://nmimusic.github.io/'
languageCode = 'ja-jp'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'Nippon Ruritania 中村音楽工業'
theme = 'universal'

[params]
	viewMorePostLink = ["/news/"]
	author = "Nippon Ruritania"
	defaultKeywords = ["中村音楽工業", "中村音工", "RURITANIA", "同人音楽", "日本ルリタニア"]
	mainSections = ["news", "blog", "music", "games", "others", "creators", "support"]

	about_us = "<p>一般社団同人中村音楽工業は、音楽制作を行なう長野県の同人クラブである。</p>"
	copyright = "Copyright (C) 2023-2026 Nakamura Musical Industries/NIPPON RURITANIA all rights reserved."

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	dropdown_mouse_over = false

	disabled_logo = false
	logo_text = "NIPPON RURITANIA"

	logo = "/img/logo.png"
	logo_small = "/img/logo.png"

	capitalizeListTitles = false
	pluralizeListTitles = false
	preserveTaxonomyNames = true

	buildFuture = true

[markup.goldmark.renderer]
	unsafe = true

[params.topbar]
	enable = true
	text = """<a href="/text/index.htm">w3m、Lynx等でご覧の方はこちら"""

[params.widgets]
	categories = true
	tags = true
	search = true

[params.carouselHomepage]
	enable = true
	auto_play = true
	slide_speed = 2000
	pagination_speed = 1000

[params.recent_news]
	enable = true
	title = "NEWS"
	hide_summary = false

[params.recent_blog]
	enable = true
	title = "BLOG"
	hide_summary = false

[params.recent_music]
	enable = true
	title = "MUSIC"
	hide_summary = false

[params.recent_games]
	enable = true
	title = "GAMES"
	hide_summary = false

[params.recent_others]
	enable = true
	title = "OTHERS"
	hide_summary = false

[params.recent_support]
	enable = true
	title = "SUPPORT"
	hide_summary = false

[params.footer.recent_posts]
    enable = true

[menu]
[[menu.main]]
	name       = "ABOUT"
	url        = "/about/"
	weight     = 1

[[menu.main]]
	name       = "NEWS"
	url        = "/news/"
	weight     = 2

[[menu.main]]
	name       = "BLOG"
	url        = "/blog/"
	weight     = 3

[[menu.main]]
	name       = "CREATORS"
	url        = "/creators/"
	weight     = 4

[[menu.main]]
	name       = "RELEASES"
	identifier = "menu.releases"
	url        = ""
	weight     = 5

[[menu.main]]
	name       = "Music"
	url        = "/music/"
	weight     = 1
	parent     = "menu.releases"

[[menu.main]]
	name       = "Games"
	url        = "/games/"
	weight     = 2
	parent     = "menu.releases"

[[menu.main]]
	name       = "Others"
	url        = "/others/"
	weight     = 3
	parent     = "menu.releases"

[[menu.main]]
	name       = "SUPPORT"
	url        = ""
	identifier = "menu.support"
	weight     = 6

[[menu.main]]
	name       = "SUPPORT INFORMATIONS"
	url        = "/support/"
	weight     = 1
	parent     = "menu.support"

[[menu.main]]
	name       = "WHAT'S CD-EXTRA?"
	url        = "/cdextra/"
	weight     = 2
	parent     = "menu.support"

[[menu.main]]
	name       = "DSD-DF COMPATIBLE LIST"
	url        = "/dsd-disc-compatible-list/"
	weight     = 3
	parent     = "menu.support"

[[menu.main]]
	name       = "DOWNLOAD WITH MUSIC CARD"
	url        = "/musiccard/"
	weight     = 4
	parent     = "menu.support"

[[menu.main]]
	name       = "FAQ"
	url        = "/faq/"
	weight     = 5
	parent     = "menu.support"

[[menu.main]]
	name       = "SHOP"
        url        = ""
	identifier = "menu.shop"
	weight     = 7

[[menu.main]]
        name       = "RURITANIA MUSIC STORE"
        url        = "https://nmimusic.booth.pm/"
        weight     = 1
        parent     = "menu.shop"

[[menu.main]]
        name       = "Melon Books"
        url        = "https://www.melonbooks.co.jp/"
        weight     = 2
        parent     = "menu.shop"

[[menu.main]]
        name       = "DLsite"
        url        = "https://www.dlsite.com/home/"
        weight     = 3
        parent     = "menu.shop"

[[menu.main]]
	name       = "OTHERS"
	url        = ""
	identifier = "menu.others"
	weight     = 8

[[menu.main]]
	name       = "LINKS"
	url        = "/links/"
	weight     = 1
	parent     = "menu.others"

[[menu.main]]
	name       = "CONTACT"
	url        = "/contact/"
	weight     = 2
	parent     = "menu.others"
	
[[menu.main]]
	name       = "POLICIES"
	url        = "/policies/"
	weight     = 3
	parent     = "menu.others"
